# .github/workflows/ui-ci.yml

name: UI CI/CD

on:
  push:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout UI Repository
        uses: actions/checkout@v2

    #   - name: Install Dependencies
    #     run: npm install --force
        
      - name: Trigger Cypress Tests
        uses: peter-evans/repository-dispatch@v1
        with:
            repository: GuiGoCa/Cypress-tst-automations
            token: ${{ secrets.GITHUB_TOKEN }}
            event-type: run-cypress-tests
      # Add other build and deployment steps as needed

