# .github/workflows/ui-ci.yml

name: CI E2E TEST

on:
  push:
    branches:
      ["main"]
  
jobs:
  e2e-tests:
    
    permissions:
        id-token: write
        contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout e2e UI Repository
        uses: actions/checkout@v2
        with: 
          repository: GuiGoCa/Cypress-tst-automations
          
      - name: use node js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: install dependencies
        run: npm ci

      - name: execute e2e ui tests
        uses: cypress-io/github-actions@v4
        with: 
          browser: chrome


