# .github/workflows/ui-ci.yml

name: UI CI/CD

on:
  push:
    branches:
      ["main"]

jobs:
  ui-tests:
    permissions:
        id-token: write
        contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout UI Repository
        uses: actions/checkout@v2


    #   - name: Install Dependencies
    #     run: npm install --force # No need to install in this project
        
      - name: Trigger Cypress Tests Ultimate
        run: |
            curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"\
            https://api.github.com/repos/GuiGoCa/Cypress-tst-automations/dispatches\
            -d '{"event_type": "run-cypress-tests"}'    
        





        # uses: peter-evans/repository-dispatch@v1
        # with:
        #     repository: GuiGoCa/Cypress-tst-automations
        #     token: ${{ secrets.GITHUB_TOKEN }}
        #     event-type: run-cypress-tests
      # Add other build and deployment steps as needed

