# .github/workflows/ui-ci.yml

name: CI Cypress E2E
run-name: ${{ github.actor }} is uploading a test in another branch

on:
  push:
    branches:
      ["main"]
  pull_request:
    branches:
      ["main"]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout e2e UI Repository
        uses: actions/checkout@v4
        with:
          repository: GuiGoCa/Cypress-tst-automations
        
      # - name: use node js 18
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18.x

      # - name: install dependencies
      #   run: npm ci

      - name: execute e2e ui tests
        uses: cypress-io/github-action@v6
        with: 
          browser: chrome


